version: "3.9"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 15s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES=${DB_NAME_APPLICATION},${DB_NAME_KEYCLOAK}
    volumes:
      - ./docker_postgres_init.sh:/docker-entrypoint-initdb.d/docker_postgres_init.sh

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_USERNAME}
      - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin:rw

  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:latest
    restart: unless-stopped
    ports:
      - "8081:8080"
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=${KC_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB=${KC_DB}
      - KC_DB_URL=${KC_DB_URL}
      - KC_DB_USERNAME=${DB_USER}
      - KC_DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - keycloak:/opt/keycloak/data:rw

volumes:
  postgres:
    external: false
  pgadmin:
    external: false
  keycloak:
    external: false