server:
  port: 8080

spring:
  application:
    name: ponto
  datasource:
    url: jdbc:postgresql://localhost:5432/ponto
    username: ${DB_USER}
    password:  ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ponto
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

custom:
  keycloak:
    url: http://localhost:8081/
    admin:
      client: admin-cli
      secret: ${KC_SECRET_ADMIN}
      username: ${KC_ADMIN_USER}
      password: ${KC_ADMIN_PASSWORD}
      realm: master
    user:
      client: ${KC_USER}
      secret: ${KC_SECRET_USER}
      realm: ponto