server:
  port: 8080

spring:
  application:
    name: ponto
  datasource:
    url: jdbc:postgresql://localhost:5432/ponto
    username: ${DB_USER}
    password:  ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  freemarker:
    template-loader-path: classpath:/templates
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/ponto
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

custom:
  keycloak:
    url: http://localhost:8081/
    admin:
      client: admin-cli
      secret: MthhgPY18p9xGg3uxyBTM2t5AULCSj7W
      username: admin
      password: admin
      realm: master
    user:
      client: desenvolvimento
      secret: vQHuCt85w7rMQc4boaQVnMe2EnlfERxE
      realm: ponto
  auth:
    key: 5gc%CjDCUb
    secret: 2S@SngVQ||sWs1f
